{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "minio.fullname" . }}-console
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.console.host }}
      secretName: minio-console-tls
  rules:
    - host: {{ .Values.ingress.console.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "minio.fullname" . }}
                port:
                  name: console
{{- end }}
